name: CI

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: npm install

    - run: echo "::set-output name=version::`./server.js --print --unhandled-rejections=strict`"
      id: update

    - uses: stefanzweifel/git-auto-commit-action@v5.0.0
      if: steps.update.outputs.version != ''
      id: "auto-commit-action"
      with:
        branch: master
        commit_message: ${{steps.update.outputs.version}}
        tagging_message: ${{steps.update.outputs.version}}

    - uses: actions/setup-node@v4
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      with:
        registry-url: https://registry.npmjs.org/
    - run: npm publish
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    - uses: actions/setup-node@v4
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      with:
        registry-url: https://npm.pkg.github.com/
        scope: '@projectlint'
    - run: npm publish
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
