name: CI

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
    - run: npm install
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Update data
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@projectlint'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
